### ISSUE TITLE
Consertar PHP compose

### ISSUE THREAD

**Issue by iuriguilherme** [temblog/grav-docker#1]
Aqui tem um passo a passo de como foi instalado o php compose no servidor onde estão os sites que usam grav <https://naoenoveladasoito.com.br> e <https://anais.tem.blog.br>:

<https://iikb.org/forum/Grav/#index3h1>

No caso o sistema operacional do hypervisor é debian jessie, mas deve servir como guia pra fazer a mesma coisa no alpine.

*Edição: eu to falando besteira, nesse "passo a passo" ta faltando justamente a parte de instalar o compose*

**Comment by littlejuh** [comment]
Corrigido! :)
